### ISSUE TITLE
Add the support for optional dependencies

### ISSUE THREAD

**Issue by liesrock** [ADVRHumanoids/forest#52]
Would it be possible to have a feature as described in the title?

To be more clear, let's take as an example the model of a robot when working in simulation and in the real robot:

- on simulation (maybe) I want to have all the dependencies, including the gazebo plugin for the sensors,
- on the real robot I just want to have the minimal model of the robot description

What do you think?

**Comment by MarcoRuzzon** [comment]
You could either have one set of recipes for simulation and one set for the real robot. But I don't know if this approach would scale very well, so I really like your suggestion. We already support args for compilation flags we could add support also for conditional dependencies.

**Comment by MarcoRuzzon** [comment]
Actually, @alaurenzi already implemented this: you need to use the _depends_if_ field
You can see a recipe example [here](https://github.com/ADVRHumanoids/multidof_recipes/blob/master/recipes/xbot2.yaml) (xbot2).

Xenomai is a dependency only if the option -m xeno is passed to forest grow

```
forest grow xbot2 -m xeno
```

FYI @EdoardoRomiti
